package com.plusorminustwo.postmark.data.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.plusorminustwo.postmark.data.db.entity.ScheduledMessageEntity
import kotlinx.coroutines.flow.Flow

/**
 * DAO for the `scheduled_messages` table (text-only "Schedule send" rows).
 *
 * Intentionally minimal: a scheduled row is created once, observed by the open thread so its
 * bubble appears/vanishes live, read by id when its WorkManager job fires, and deleted when it
 * sends / is cancelled / is edited. It never participates in sync, search, or stats.
 */
@Dao
interface ScheduledMessageDao {

    /** Inserts a new scheduled row; returns its autoGenerated id (also the WorkManager job key). */
    @Insert
    suspend fun insert(row: ScheduledMessageEntity): Long

    @Query("DELETE FROM scheduled_messages WHERE id = :id")
    suspend fun deleteById(id: Long)

    @Query("SELECT * FROM scheduled_messages WHERE id = :id")
    suspend fun getById(id: Long): ScheduledMessageEntity?

    /** This thread's scheduled sends, soonest first — backs the scheduled bubble section so it
     *  updates live as rows are added or fire. */
    @Query("SELECT * FROM scheduled_messages WHERE threadId = :threadId ORDER BY scheduledAt ASC")
    fun observeByThread(threadId: Long): Flow<List<ScheduledMessageEntity>>

    /** Every scheduled row (any thread), soonest first — reserved for reschedule-on-boot style
     *  sweeps; WorkManager already persists its own queue across reboots. */
    @Query("SELECT * FROM scheduled_messages ORDER BY scheduledAt ASC")
    suspend fun getAll(): List<ScheduledMessageEntity>
}
